config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :moves do
      get "new/:position", to: "moves#new", on: :collection, as: 'new'
    end
    get 'rematch', to: 'games#rematch'
  end
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unlock', registration: 'register', sign_up: 'cmon_let_me_in' }  

  root 'games#index'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id         :integer          not null, primary key
#  status     :string
#  player1_id :integer
#  player2_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Game < ActiveRecord::Base
  belongs_to :player1, class_name: 'User', foreign_key: 'player1_id'
  belongs_to :player2, class_name: 'User', foreign_key: 'player2_id'
  belongs_to :winner, class_name: 'User', foreign_key: 'winner_id'

  has_many :moves
  
  def players
    [self.player1, self.player2]
  end
  
  validates :player1_id, presence: true
  validates :player2_id, presence: true
  
  def next_player
    if self.moves.empty?
      return player1
    else
      return self.player2 if self.moves.last.player == self.player1
      return self.player1 if self.moves.last.player == self.player2      
    end
  end
  
  def check_for_winner
    return winner if self.winner
    return nil if self.status != 'In progress'
        
    winning_combinations = [[0, 1, 2], [0, 3, 6], [0, 4, 8], [1, 4, 7], [2, 4, 6], [2, 5, 8], [3, 4, 5], [6, 7, 8]]
    
    check = {}
    
    self.players.each do |player|
      check[player.id] = [] unless check[player.id]
      self.moves.map{|move| check[player.id] << move.position if move.player == player }
      
      winning_combinations.each do |win|
        if check[player.id].is_a? Array and check[player.id].any? and (win - check[player.id]).empty?
          winner = player 
          self.status = 'Finished'
          self.winner_id = winner.id
          self.save
        end
      end      
    end
    
    return winner ? winner : false
  end  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = current_user.games.select { |game| game.status == 'In progress' }
  end

  # GET /games/1
  # GET /games/1.json
  def show
    if request.xhr?
      render partial: 'game_board', locals: { game: @game }
    else
      render :show
    end    
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end
  
  def rematch
    @game = Game.find(params[:game_id])
    other_players = @game.players.select{|player| player != current_user}
    @new_game = Game.new
    @new_game.player1 = current_user
    @new_game.player2 = other_players.first
    @new_game.status = 'In progress'
    if @new_game.save
      redirect_to game_path @new_game, notice: 'Game created.  Your turn.'
    else
      redirect_to new_game_path
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    
    player2 = User.where(username: params[:game][:player2])
    if player2.any?
    @game.player2_id = player2.first.id 
    else
      return redirect_to new_game_path, flash: { danger: "Can't find that player" }
    end
    
    @game.player1_id = current_user.id
    @game.status = "In progress"    
      
    return redirect_to games_path, flash: { danger: "Don't be silly." } if @game.player2 == @game.player1
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player2_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def stats
    content_tag :h4, "Played #{current_user.games.count} | Won #{current_user.winners.count}"   
  end
  
  def render_game(game)
    rows = 3
    cols = 3
    
    content = ''.html_safe
    count = 0
    
    moves = {}
    game.moves.each do |move|
      moves[move.position] = move
    end
    
    current_user_move = (game.moves.empty? and game.player1 == current_user) || (game.moves.any? and game.moves.last.player != current_user) rescue false
            
    (1..rows).each do |row|
      row_content = ''.html_safe
      (1..cols).each do |col|
        
        row_content += content_tag :td, class: "#{current_user_move ? 'space' : 'disabled'}", data: { space: count } do
          if moves[count]
            token = content_tag :span, '&times'.html_safe, class: 'player1' if moves[count].player.username == game.player1.username            
            token = content_tag :span, '&#x25CF;'.html_safe, class: 'player2' if moves[count].player.username == game.player2.username
            token
          else
            link_to '&nbsp;'.html_safe, new_game_moves_path(game, count), class: 'btn btn-success alert-success btn-block' if current_user_move and !game.check_for_winner
          end
        end
        count += 1
      end
      
      content += content_tag :tr do
        row_content
      end
    end
    
    content_tag :table, class: 'noughts-and-crosses-board' do
      content
    end
  end
end

app/views/games/_form.html.erb
<%= form_for(@game, html: { class: 'form-horizontal'}) do |f| %>
  <% if @game.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</strong>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :enter_the_username_of_an_opponent, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :player2, class: 'form-control' %>
      <%= content_tag :p, 'Case sensitive', class: 'help-block' %>
    </div>
  </div>

  <div class="form-group">
    <div class="btn-group col-md-9 col-md-offset-3">
      <%= f.submit 'Create', class: 'btn btn-success' %>
      <%= link_to 'Cancel', games_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <a href="<%= game_path(game) %>">
        <%= game.player1.username %> vs <%= game.player2.username %>
      </a>
    </h3>
  </div>



  <div class="panel-body game-container <%= 'game-container-loader' if game.status == 'In progress' %>" data-url="<%= game_path(game) %>">
    <%= render partial: 'game_board', locals: {game: game} %>
  </div>      
</div>

app/views/games/_game_board.html.erb
<% if game.check_for_winner %>
  <div class="alert alert-<%= game.check_for_winner == current_user ? 'success' : 'danger' %>">
    <%= game.check_for_winner == current_user ? 'You win!' : game.check_for_winner.username + ' has won' %>
    <%= link_to 'Rematch', game_rematch_path(game), class: 'alert-link pull-right' %>
  </div>
<% end %>   

<% if game.status == 'Draw' %>
  <div class="alert alert-warning">
    Draw.  You're both losers.
    <%= link_to 'Rematch', game_rematch_path(game), class: 'alert-link pull-right' %>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-8">
      <%= render_game(game) %>
  </div>
  <div class="col-sm-4 players">
    <% [[game.player1, '&times;'], [game.player2, '&#x25CF;']].each_with_index do |player, index| %>
      <% current_user_move = game.next_player.username == player[0].username  %>
      <% current_user_move = false if ['Finished', 'Draw'].include? game.status %>
      <h4><span class="player<%= index + 1 %> label<%= ' current_user_move' if current_user_move %>"><%= current_user == player[0] ? 'You' : player[0].username %> <span class="player-icon"><%= player[1].html_safe %></span></span></h4>      
    <% end %>

    <p>Created <%= time_ago_in_words game.created_at %> ago</p>
    <% if game.moves.any? %><p>Last move <%= time_ago_in_words game.moves.last.created_at %> ago</p><% end %>
    <p><strong><%= game.status.gsub('In progress', (game.next_player == current_user ? 'Your turn' : "Waiting for #{game.next_player.username}")) %></strong></p>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<%= link_to 'New Game', new_game_path, class: 'btn btn-success pull-right' %>

<h2>Noughts and Crosses</h2>

<%= stats %>

<% @games.each do |game| %>
  <%= render partial: 'game', locals: { game: game } %>
<% end %>

<% if @games.empty? %>
<div class="alert alert-warning"><span class="glyphicon glyphicon-exclamation-sign"></span> No games currently in progress.  <%= link_to 'Create a game', new_game_path, class: 'alert-link' %></div>
<% end %>

app/views/games/new.html.erb
<h2>New Game</h2>

<%= render 'form' %>

app/views/games/show.html.erb
<h2>Noughts and Crosses</h2>

<%= stats %>

<%= render partial: 'game', locals: { game: @game } %>

<%= link_to 'View all games in progress', games_path, class: 'btn btn-default' %>